codestyle:
  stage: test
  cache: {}
  script:
    - composer require overtrue/phplint --dev -vvv -n
    - echo "Started linting with phplint"
    - ./vendor/bin/phplint ./ --exclude=vendor

phpunit:
  stage: test
  script:
    - echo "Tests"

deploy:
  stage: deploy
  script:
    - echo "Deployment to the server is happening here"
