image: gradle:alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle
stages:
  - sonar
  - validate
  - build
  - test
build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle   
checkstyle:
  stage: validate
  script:
    -  java -jar checkstyle-8.36.2-all.jar -c google_checks.xml .
  allow_failure: true
staticanalysis:
  stage: validate
  script:
    - gradle validate
  allow_failure: true
sonarqube:
  stage: sonar
  script:
    - cd webapplication/Sticks-n-pucks
    - gradle sonarqube -Dsonar.projectKey=sticksnpucks -Dsonar.host.url=http://localhost:9000 -Dsonar.login=c14d731517eb24eef16d09d41d5f9791df9791af
testapi:
  stage: test
  script: 
    - cd api/sticks-pucks
    - gradle clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
testweb:
  stage: test
  script: 
    - cd webapplication/Sticks-n-pucks
    - gradle clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
