image: gradle:alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle
stages:
  - validate
  - build
  - test
  - sonar
checkstyle:
  stage: validate
  script:
    -  java -jar checkstyle-8.36.2-all.jar -c google_checks.xml .
  allow_failure: true
build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle   
testapi:
  stage: test
  script: 
    - cd api/sticks-pucks
    - gradle clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
testweb:
  stage: test
  script: 
    - cd webapplication/Sticks-n-pucks
    - gradle clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
sonarqube-web:
  stage: sonar
  script:
    - cd webapplication/Sticks-n-pucks
    - gradle sonarqube
  allow_failure: true
sonarqube-api:
  stage: sonar
  script:
    - cd api/sticks-pucks
    - gradle sonarqube
  allow_failure: true