image: gradle:alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - docker
  - setup
  - build
  - test
  - codequality
  - sonar

build-docker:
  stage: docker
  script:
    - cd webapplication/Sticks-n-pucks
    - docker build -t sticks-n-pucks .
  allow_failure: true


checkstyle:
  stage: codequality
  script:
    -  java -jar checkstyle-8.36.2-all.jar -c google_checks.xml .
  allow_failure: true

javadocapi:
  stage: codequality
  script:
    - cd api/sticks-pucks
    - gradle javadoc
  allow_failure: true

javadocweb:
  stage: codequality
  script:
    - cd webapplication/Sticks-n-pucks
    - gradle javadoc
  allow_failure: true

setup-web:
  stage: setup
  script:
    - cd webapplication/Sticks-n-pucks/frontend
    - npm install

build-api:
  stage: build
  script:
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  allow_failure: true

build-web:
  stage: build
  script:
    - cd webapplication/Sticks-n-pucks
    - # gradle build --scan
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


testapi:
  stage: test
  script: 
    - cd api/sticks-pucks
    - gradle clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

testweb:
  stage: test
  script: 
    - gradle test
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

sonarqube-web:
  stage: sonar
  script:
    - cd webapplication/Sticks-n-pucks
    - gradle sonarqube
  allow_failure: true

sonarqube-api:
  stage: sonar
  script:
    - cd api/sticks-pucks
    - gradle sonarqube
  allow_failure: true

after_script:
  - echo "The pipeline ended"