image: lorisleiva/laravel-docker:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

codestyle:
  stage: test
  cache: {}
  script:
    - composer require overtrue/phplint --dev -vvv -n
    - echo "Started linting with phplint"
    - ./vendor/bin/phplint ./ --exclude=vendor

phpunit:
  stage: test
  script:
    - echo "Tests"
